In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("melb_data.csv")

<li>Rooms: Number of rooms</li>
<li>Price: Price in dollars</li>
<li>Method: S - property sold; SP - property sold prior; PI - property passed in; PN - sold prior not disclosed; SN - sold not disclosed; NB - no bid; VB - vendor bid; W - withdrawn prior to auction; SA - sold after auction; SS - sold after auction price not disclosed. N/A - price or highest bid not available.</li>
<li>Type: br - bedroom(s); h - house,cottage,villa, semi,terrace; u - unit, duplex; t - townhouse; dev site - development site; o res - other residential.</li>
<li>SellerG: Real Estate Agent</li>
<li>Date: Date sold</li>
<li>Distance: Distance from CBD</li>
<li>Regionname: General Region (West, North West, North, North east …etc)</li>
<li>Propertycount: Number of properties that exist in the suburb.</li>
<li>Bedroom2 : Scraped # of Bedrooms (from different source)</li>
<li>Bathroom: Number of Bathrooms</li>
<li>Car: Number of carspots</li>
<li>Landsize: Land Size</li>
<li>BuildingArea: Building Size</li>
<li>CouncilArea: Governing council for the area</li>

In [3]:
df.head()

Suburb           Address  Rooms Type      Price Method SellerG  \
0  Abbotsford      85 Turner St      2    h  1480000.0      S  Biggin   
1  Abbotsford   25 Bloomburg St      2    h  1035000.0      S  Biggin   
2  Abbotsford      5 Charles St      3    h  1465000.0     SP  Biggin   
3  Abbotsford  40 Federation La      3    h   850000.0     PI  Biggin   
4  Abbotsford       55a Park St      4    h  1600000.0     VB  Nelson   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
1  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
2  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   
3  4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0           NaN   
4  4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0         142.0   

   YearBuilt  CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN        Yarra  -37.7996    144.9984  Northern Metropolitan   
1     1900.0        Yarra  -37.8079    144.9934  Northern Metropolitan   
2     1900.0        Yarra  -37.8093    144.9944  Northern Metropolitan   
3        NaN        Yarra  -37.7969    144.9969  Northern Metropolitan   
4     2014.0        Yarra  -37.8072    144.9941  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Suburb         13580 non-null  object 
 1   Address        13580 non-null  object 
 2   Rooms          13580 non-null  int64  
 3   Type           13580 non-null  object 
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object 
 6   SellerG        13580 non-null  object 
 7   Date           13580 non-null  object 
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object 
 17  Lattitude      13580 non-null  float64
 18  Longti

In [5]:
df.isnull().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

In [6]:
df.shape

(13580, 21)

In [7]:
df.describe()

Rooms         Price      Distance      Postcode      Bedroom2  \
count  13580.000000  1.358000e+04  13580.000000  13580.000000  13580.000000   
mean       2.937997  1.075684e+06     10.137776   3105.301915      2.914728   
std        0.955748  6.393107e+05      5.868725     90.676964      0.965921   
min        1.000000  8.500000e+04      0.000000   3000.000000      0.000000   
25%        2.000000  6.500000e+05      6.100000   3044.000000      2.000000   
50%        3.000000  9.030000e+05      9.200000   3084.000000      3.000000   
75%        3.000000  1.330000e+06     13.000000   3148.000000      3.000000   
max       10.000000  9.000000e+06     48.100000   3977.000000     20.000000   

           Bathroom           Car       Landsize  BuildingArea    YearBuilt  \
count  13580.000000  13518.000000   13580.000000   7130.000000  8205.000000   
mean       1.534242      1.610075     558.416127    151.967650  1964.684217   
std        0.691712      0.962634    3990.669241    541.014538    37.273762   
min        0.000000      0.000000       0.000000      0.000000  1196.000000   
25%        1.000000      1.000000     177.000000     93.000000  1940.000000   
50%        1.000000      2.000000     440.000000    126.000000  1970.000000   
75%        2.000000      2.000000     651.000000    174.000000  1999.000000   
max        8.000000     10.000000  433014.000000  44515.000000  2018.000000   

          Lattitude    Longtitude  Propertycount  
count  13580.000000  13580.000000   13580.000000  
mean     -37.809203    144.995216    7454.417378  
std        0.079260      0.103916    4378.581772  
min      -38.182550    144.431810     249.000000  
25%      -37.856822    144.929600    4380.000000  
50%      -37.802355    145.000100    6555.000000  
75%      -37.756400    145.058305   10331.000000  
max      -37.408530    145.526350   21650.000000

In [8]:
y = df["Price"]
y.head()

0    1480000.0
1    1035000.0
2    1465000.0
3     850000.0
4    1600000.0
Name: Price, dtype: float64

In [9]:
df.Price.describe([.2, .4, .6, .8])

count    1.358000e+04
mean     1.075684e+06
std      6.393107e+05
min      8.500000e+04
20%      6.000000e+05
40%      8.000000e+05
50%      9.030000e+05
60%      1.040000e+06
80%      1.450000e+06
max      9.000000e+06
Name: Price, dtype: float64

In [10]:
# df_num as numeric_features.
numeric_features = df.select_dtypes(['int', 'float']).columns
numeric_features , len(numeric_features)

(Index(['Price', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
        'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude', 'Longtitude',
        'Propertycount'],
       dtype='object'),
 12)

In [11]:
# df_cat as categorical_features.
categorical_features = df.select_dtypes('object').columns
categorical_features, len(categorical_features)

(Index(['Suburb', 'Address', 'Type', 'Method', 'SellerG', 'Date', 'CouncilArea',
        'Regionname'],
       dtype='object'),
 8)

In [12]:
print("Number of `Numerical` Features are:", len(numeric_features) )
print("Number of `Categorical` Features are:", len(categorical_features) )
print("`Total Number` of features are :", len(numeric_features | categorical_features) )

Number of `Numerical` Features are: 12
Number of `Categorical` Features are: 8
`Total Number` of features are : 20


In [13]:
df.isna().sum().sort_values(ascending=False)

BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Car                62
Propertycount       0
Date                0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Bedroom2            0
Distance            0
Postcode            0
Regionname          0
Bathroom            0
Landsize            0
Lattitude           0
Longtitude          0
Suburb              0
dtype: int64

In [14]:
df[["BuildingArea","YearBuilt","CouncilArea","Car"]].describe(include="all")

BuildingArea    YearBuilt CouncilArea           Car
count    7130.000000  8205.000000       12211  13518.000000
unique           NaN          NaN          33           NaN
top              NaN          NaN    Moreland           NaN
freq             NaN          NaN        1163           NaN
mean      151.967650  1964.684217         NaN      1.610075
std       541.014538    37.273762         NaN      0.962634
min         0.000000  1196.000000         NaN      0.000000
25%        93.000000  1940.000000         NaN      1.000000
50%       126.000000  1970.000000         NaN      2.000000
75%       174.000000  1999.000000         NaN      2.000000
max     44515.000000  2018.000000         NaN     10.000000

In [15]:
df["CouncilArea"] = df["CouncilArea"].fillna("Moreland")
df["YearBuilt"] = df["YearBuilt"].fillna(df["YearBuilt"].mode()[0])
df["BuildingArea"] = df["BuildingArea"].fillna(df["BuildingArea"].mean())
df["Car"] = df["Car"].fillna(df["Car"].median())

In [16]:
df.BuildingArea.describe()

count    13580.000000
mean       151.967650
std        392.002962
min          0.000000
25%        122.000000
50%        151.967650
75%        151.967650
max      44515.000000
Name: BuildingArea, dtype: float64

In [17]:
# Now, is there any missing values are there?
df.isna().any()

Suburb           False
Address          False
Rooms            False
Type             False
Price            False
Method           False
SellerG          False
Date             False
Distance         False
Postcode         False
Bedroom2         False
Bathroom         False
Car              False
Landsize         False
BuildingArea     False
YearBuilt        False
CouncilArea      False
Lattitude        False
Longtitude       False
Regionname       False
Propertycount    False
dtype: bool

In [18]:
# Categorical Features

In [19]:
print("Total Records :", len(df) )
for col in categorical_features:
    print("Total Unique Records of "+ col + " =",  len(df[col].unique()))

Total Records : 13580
Total Unique Records of Suburb = 314
Total Unique Records of Address = 13378
Total Unique Records of Type = 3
Total Unique Records of Method = 5
Total Unique Records of SellerG = 268
Total Unique Records of Date = 58
Total Unique Records of CouncilArea = 33
Total Unique Records of Regionname = 8


In [20]:
# Removing columns which has huge number of unique values

In [21]:
categorical_features = categorical_features.drop("Address")
categorical_features = categorical_features.drop("SellerG")
categorical_features = categorical_features.drop("Suburb")

In [22]:
# Let's see again the number of unique records
print("Total Records :", len(df) )
for col in categorical_features:
    print("Total Unique Records of "+ col + " =",  len(df[col].unique()))

Total Records : 13580
Total Unique Records of Type = 3
Total Unique Records of Method = 5
Total Unique Records of Date = 58
Total Unique Records of CouncilArea = 33
Total Unique Records of Regionname = 8


In [23]:
corr = df[numeric_features].corr()
corr

Price  Distance  Postcode  Bedroom2  Bathroom       Car  \
Price          1.000000 -0.162522  0.107867  0.475951  0.467038  0.239109   
Distance      -0.162522  1.000000  0.431514  0.295927  0.127155  0.260596   
Postcode       0.107867  0.431514  1.000000  0.060584  0.113664  0.050514   
Bedroom2       0.475951  0.295927  0.060584  1.000000  0.584685  0.403867   
Bathroom       0.467038  0.127155  0.113664  0.584685  1.000000  0.321014   
Car            0.239109  0.260596  0.050514  0.403867  0.321014  1.000000   
Landsize       0.037507  0.025004  0.024558  0.025646  0.037130  0.026780   
BuildingArea   0.069570  0.073990  0.040714  0.089102  0.084462  0.068276   
YearBuilt     -0.259387  0.194815  0.025400 -0.041331  0.113957  0.078696   
Lattitude     -0.212934 -0.130723 -0.406104  0.015925 -0.070594 -0.002023   
Longtitude     0.203656  0.239425  0.445357  0.102238  0.118971  0.062929   
Propertycount -0.042153 -0.054910  0.062304 -0.081350 -0.052201 -0.024344   

               Landsize  BuildingArea  YearBuilt  Lattitude  Longtitude  \
Price          0.037507      0.069570  -0.259387  -0.212934    0.203656   
Distance       0.025004      0.073990   0.194815  -0.130723    0.239425   
Postcode       0.024558      0.040714   0.025400  -0.406104    0.445357   
Bedroom2       0.025646      0.089102  -0.041331   0.015925    0.102238   
Bathroom       0.037130      0.084462   0.113957  -0.070594    0.118971   
Car            0.026780      0.068276   0.078696  -0.002023    0.062929   
Landsize       1.000000      0.094659   0.008806   0.009695    0.010833   
BuildingArea   0.094659      1.000000   0.005178   0.031799   -0.017441   
YearBuilt      0.008806      0.005178   1.000000   0.046718   -0.000515   
Lattitude      0.009695      0.031799   0.046718   1.000000   -0.357634   
Longtitude     0.010833     -0.017441  -0.000515  -0.357634    1.000000   
Propertycount -0.006854     -0.020736   0.004421   0.047086    0.065988   

               Propertycount  
Price              -0.042153  
Distance           -0.054910  
Postcode            0.062304  
Bedroom2           -0.081350  
Bathroom           -0.052201  
Car                -0.024344  
Landsize           -0.006854  
BuildingArea       -0.020736  
YearBuilt           0.004421  
Lattitude           0.047086  
Longtitude          0.065988  
Propertycount       1.000000

In [24]:
df[categorical_features].value_counts()

Type  Method  Date        CouncilArea  Regionname                
h     S       23/09/2017  Moreland     Western Metropolitan          43
              3/09/2017   Moreland     Northern Metropolitan         40
              23/09/2017  Moreland     Northern Metropolitan         39
              16/09/2017  Moreland     Northern Metropolitan         38
              19/08/2017  Moreland     Northern Metropolitan         36
                                                                     ..
t     S       19/11/2016  Maribyrnong  Western Metropolitan           1
                          Hobsons Bay  Western Metropolitan           1
              19/08/2017  Moreland     South-Eastern Metropolitan     1
              18/06/2016  Yarra        Northern Metropolitan          1
h     PI      1/07/2017   Banyule      Eastern Metropolitan           1
Length: 5229, dtype: int64

In [25]:
# Here we need to define feature_columns the we convert to number in the below cell

categorical_features = ["Type","Method","CouncilArea", "Regionname"]
categorical_features

['Type', 'Method', 'CouncilArea', 'Regionname']

In [26]:
#  Import LabelEncoder from sklearn.preproccessing module
from sklearn.preprocessing import LabelEncoder

In [27]:
# Encoding ...
for column in categorical_features:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])

In [28]:
# Creating Training Feature to train the model to predict the beter accuracy.

In [29]:
df_final = list(numeric_features) + list(categorical_features)

# Remove 'Price' Feature from list
df_final.remove("Price")

# show the final list
df_final

['Distance',
 'Postcode',
 'Bedroom2',
 'Bathroom',
 'Car',
 'Landsize',
 'BuildingArea',
 'YearBuilt',
 'Lattitude',
 'Longtitude',
 'Propertycount',
 'Type',
 'Method',
 'CouncilArea',
 'Regionname']

In [30]:
from sklearn.preprocessing import MinMaxScaler

In [31]:
mm = MinMaxScaler()
mm.fit(df[df_final])

MinMaxScaler()

In [32]:
X = mm.transform(df[df_final])
y = df["Price"] 

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [34]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1)

In [35]:
print("Total size: ", df.shape[0])
print("Train size - Training: ", X_train.shape,y_train.shape)
print("Test size - Testing: ",X_test.shape,y_test.shape)

Total size:  13580
Train size - Training:  (9506, 15) (9506,)
Test size - Testing:  (4074, 15) (4074,)


In [36]:
lin = LinearRegression()
lin.fit(X_train,y_train)

LinearRegression()

In [37]:
lin.score(X_train,y_train)

0.5743214870733868

In [38]:
lin.score(X_test,y_test)

0.23913150206003198

In [39]:
lin.coef_

array([-2.31974886e+06,  8.89831924e+05,  2.73448835e+06,  1.86347744e+06,
        4.67401357e+05,  6.93618417e+06,  2.44181704e+07, -2.36761510e+06,
       -7.26714244e+05,  1.28612559e+06, -2.24350258e+04, -4.60097800e+05,
       -3.50194564e+04, -1.04507160e+05,  2.37181788e+05])

In [40]:
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge

In [41]:
l2 = Ridge(8)
l2.fit(X_train,y_train)
l2.coef_

array([-2143722.52697709,   788642.15088761,  1843127.2350897 ,
        1944030.36532638,   506910.04665315,    77691.43763646,
         145749.62663453, -1335777.79703345,  -747702.89567847,
        1228377.69493915,   -21931.44168819,  -542150.77902578,
         -36465.27531515,  -109407.81451845,   232783.62553401])

In [42]:
l2.score(X_train,y_train)

0.5592572910330759

In [43]:
l2.score(X_test,y_test)

0.576459542649615

In [44]:
l1 = Lasso(8000)
l1.fit(X_train,y_train)
l1.coef_

array([-1133572.12300231,        0.        ,        0.        ,
        1804485.90349924,        0.        ,        0.        ,
              0.        ,       -0.        ,  -613399.32448905,
         514012.86281579,       -0.        ,  -598884.12604434,
             -0.        ,   -51723.65605802,    86945.91917015])

In [45]:
l1.score(X_train,y_train)

0.4429754865278813

In [46]:
l1.score(X_test,y_test)

0.45355733056703673

In [47]:
for i in range(30):
    l2 = Ridge(alpha=i)
    l2.fit(X_train,y_train)
    print(i,":",l2.score(X_test,y_test))

0 : 0.2391315020600352
1 : 0.5857597575922602
2 : 0.5842260229026733
3 : 0.5829821720490658
4 : 0.581749274697752
5 : 0.5804789443425697
6 : 0.5791691831207932
7 : 0.5778269129574203
8 : 0.576459542649615
9 : 0.5750731688731356
10 : 0.5736724445023029
11 : 0.5722608340509792
12 : 0.5708409078189363
13 : 0.5694145877669613
14 : 0.5679833337326055
15 : 0.5665482786936317
16 : 0.565110325044559
17 : 0.5636702123821702
18 : 0.5622285649212753
19 : 0.5607859245082436
20 : 0.5593427735121206
21 : 0.5578995506265516
22 : 0.556456661719997
23 : 0.5550144872366374
24 : 0.5535733872028662
25 : 0.5521337045796824
26 : 0.5506957674802274
27 : 0.5492598906162398
28 : 0.5478263762277504
29 : 0.5463955146732087


In [48]:
for i in range(100,800,50):
    l1 = Lasso(alpha=i)
    l1.fit(X_train,y_train)
    print(i,":",l1.score(X_test,y_test))

100 : 0.5858393347941275
150 : 0.5832229677625209
200 : 0.583205385711894
250 : 0.5831625299914709
300 : 0.5830944006012516
350 : 0.5830009975412361
400 : 0.5828823208114247
450 : 0.5827383704118168
500 : 0.582569146342413
550 : 0.5823746487441492
600 : 0.5821548775091346
650 : 0.5819098326104044
700 : 0.5816395140479582
750 : 0.5813439218217964


In [49]:
from sklearn.model_selection import cross_val_score

In [50]:
l2_final = Ridge(1)
l1_final = Lasso(100)

In [51]:
l2_cross = cross_val_score(l2_final,X,y,cv=4)

In [52]:
l2_cross

array([0.60612736, 0.56034392, 0.56284609, 0.47008509])

In [53]:
np.mean(l2_cross)

0.5498506148379206

In [54]:
l1_cross = cross_val_score(l1_final,X,y,cv=4)

In [55]:
l1_cross

array([0.60679687, 0.56127426, 0.56241941, 0.46843822])

In [56]:
np.mean(l1_cross)

0.5497321917423881